### ISSUE TITLE
your download has been stopped due to: Resource not found

### ISSUE THREAD

**Issue by gofy0004** [Sam-Max/rclone-mirror-leech-telegram-bot#103]
[botlog.txt](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/files/10719866/botlog.txt)

when i try to /mirror from jacket rss links i get this error although the official yts rss works fine
![image](https://user-images.githubusercontent.com/121460315/218401686-4e9c13a9-e002-444c-8b9d-a92069f6bee3.png)

**Comment by Sam-Max** [comment]
> [botlog.txt](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/files/10719866/botlog.txt)
> 
> when i try to /mirror from jacket rss links i get this error although the official yts rss works fine ![image](https://user-images.githubusercontent.com/121460315/218401686-4e9c13a9-e002-444c-8b9d-a92069f6bee3.png)

Not a valid link, use a direct link
