### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by killerlearner** [Sam-Max/rclone-mirror-leech-telegram-bot#104]
Can I deploy it in heroku by modifying config file and directly deploy using GitHub by connecting my GitHub account to heroku!
Or there is need to edit any other file??

**Comment by Sam-Max** [comment]
> Can I deploy it in heroku by modifying config file and directly deploy using GitHub by connecting my GitHub account to heroku! Or there is need to edit any other file??

No heroku support, your account will be banned
