### ISSUE TITLE
Not uploading 

### ISSUE THREAD

**Issue by mohamedkaissi** [Sam-Max/rclone-mirror-leech-telegram-bot#105]
Stuck here , I've tried to restart and rebuild docker image still same problem 
![Screenshot_2023-02-25-17-04-02-355-edit_uz unnarsx cherrygram](https://user-images.githubusercontent.com/62901183/221367162-31d7803e-05db-498b-9b94-07892f0fc608.jpg)

**Comment by Sam-Max** [comment]
Report any issued on telegram channel, https://t.me/rcmltb
