### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 320cuneyt** [Sam-Max/rclone-mirror-leech-telegram-bot#115]
When I select a single file from Dropbox, it downloads, but when I select all the files in the folder, it gives an error.
![IMG_20230228_214202](https://user-images.githubusercontent.com/115102258/221948957-7177a6bb-1695-4b1c-ba8d-8bafbca76362.jpg)
@
[botlog (3).txt](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/files/10853744/botlog.3.txt)

**Comment by khainee** [comment]
Leeching?

**Comment by 320cuneyt** [comment]
yes

**Comment by khainee** [comment]
@320cuneyt i don't get error when leeching from dropbox

**Comment by khainee** [comment]
@320cuneyt did you used latest repo?

**Comment by 320cuneyt** [comment]
I installed the repository last night and got this error.

**Comment by 320cuneyt** [comment]
I reinstalled the repository.  The problem is fixed.

**Comment by 320cuneyt** [comment]
.
