### ISSUE TITLE
ImportError: cannot import name 'sre_parse'

### ISSUE THREAD

**Issue by erickyun** [Sam-Max/rclone-mirror-leech-telegram-bot#119]
Bot won't start after latest repo update? `commit 9ab9e81`
Would appreciate your help sir?

```
rcmltb | Traceback (most recent call last):
rcmltb |   File "<frozen runpy>", line 198, in _run_module_as_main
rcmltb |   File "<frozen runpy>", line 88, in _run_code
rcmltb |   File "/usr/src/app/bot/__main__.py", line 16, in <module>
rcmltb |     from .modules import batch, cancel, botfiles, copy, leech, mirror_leech, myfilesset, owner_settings, cloudselect, search, myfiles, stats, status, clone, storage, cleanup, user_settings, ytdlp, shell, exec, bt_select, rss, serve, sync
rcmltb |   File "/usr/src/app/bot/modules/batch.py", line 16, in <module>
rcmltb |     from bot.modules.mirror_leech import mirror_leech
rcmltb |   File "/usr/src/app/bot/modules/mirror_leech.py", line 13, in <module>
rcmltb |     from bot.helper.ext_utils.direct_link_generator import direct_link_generator
rcmltb |   File "/usr/src/app/bot/helper/ext_utils/direct_link_generator.py", line 21, in <module>
rcmltb |     from lk21 import Bypass
rcmltb |   File "/usr/lib/python3.11/site-packages/lk21/__init__.py", line 11, in <module>
rcmltb |     from .cli import main
rcmltb |   File "/usr/lib/python3.11/site-packages/lk21/cli.py", line 2, in <module>
rcmltb |     from .thirdparty.exrex import generate as generate_strings
rcmltb |   File "/usr/lib/python3.11/site-packages/lk21/thirdparty/exrex.py", line 25, in <module>
rcmltb |     from re import sre_parse, U
rcmltb | ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)
```

**Comment by Sam-Max** [comment]
> Bot won't start after latest repo update? `commit 9ab9e81` Would appreciate your help sir?
> 
> ```
> rcmltb | Traceback (most recent call last):
> rcmltb |   File "<frozen runpy>", line 198, in _run_module_as_main
> rcmltb |   File "<frozen runpy>", line 88, in _run_code
> rcmltb |   File "/usr/src/app/bot/__main__.py", line 16, in <module>
> rcmltb |     from .modules import batch, cancel, botfiles, copy, leech, mirror_leech, myfilesset, owner_settings, cloudselect, search, myfiles, stats, status, clone, storage, cleanup, user_settings, ytdlp, shell, exec, bt_select, rss, serve, sync
> rcmltb |   File "/usr/src/app/bot/modules/batch.py", line 16, in <module>
> rcmltb |     from bot.modules.mirror_leech import mirror_leech
> rcmltb |   File "/usr/src/app/bot/modules/mirror_leech.py", line 13, in <module>
> rcmltb |     from bot.helper.ext_utils.direct_link_generator import direct_link_generator
> rcmltb |   File "/usr/src/app/bot/helper/ext_utils/direct_link_generator.py", line 21, in <module>
> rcmltb |     from lk21 import Bypass
> rcmltb |   File "/usr/lib/python3.11/site-packages/lk21/__init__.py", line 11, in <module>
> rcmltb |     from .cli import main
> rcmltb |   File "/usr/lib/python3.11/site-packages/lk21/cli.py", line 2, in <module>
> rcmltb |     from .thirdparty.exrex import generate as generate_strings
> rcmltb |   File "/usr/lib/python3.11/site-packages/lk21/thirdparty/exrex.py", line 25, in <module>
> rcmltb |     from re import sre_parse, U
> rcmltb | ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)
> ```

After last update, you need to git clone repo again and deploy

**Comment by erickyun** [comment]
I did replace requirements.txt with latest repo.
And I did deploy again with `sudo docker-compose up --build`
But I'm still receiving this error?

Should I also terminate mongo and generate new one?

**Comment by Sam-Max** [comment]
> I did just git clone repo again and deploy But I'm still receiving this error?
> 
> Should I also terminate mongo and generate new one?

Yes, do it

**Comment by erickyun** [comment]
İt seems to work now but before it didn't know why? But thank you formyour help sir. I appreciate your work btw 👍
