### ISSUE TITLE
Disabling auto share link

### ISSUE THREAD

**Issue by undeadmecha0** [Sam-Max/rclone-mirror-leech-telegram-bot#120]
How to disable automatic file sharing for files that are uploaded in gdrive?
Every file uploaded are being shared

**Comment by Sam-Max** [comment]
> How to disable automatic file sharing for files that are uploaded in gdrive? Every file uploaded are being shared

What do you mean are being shared? Bot generates a link for the file, but only you have access to that link.

**Comment by undeadmecha0** [comment]
O
