### ISSUE TITLE
[Bug] httpx.ConnectTimeout bot won't start?

### ISSUE THREAD

**Issue by erickyun** [Sam-Max/rclone-mirror-leech-telegram-bot#122]
Hi,

After I did restart bot I keep getting httpx.ConnectTimeout error?

[Log.txt](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/files/10966318/Loghg.txt)

I would appreciate your help sir?
This happend after I forgot to close `/serve` and did execute /restart  now bot keeps giving me httpx.ConnectTimeout error?

## Edit:
Bot did give this error message on telegram when I executed restart.

```
Error: 2023/03/13 14:32:10 NOTICE: Encrypted drive 'dropbox-encrypt:': WebDav Server started on [http://[::]:8080/]
```

**Comment by Sam-Max** [comment]
Where are you deploying?

**Comment by erickyun** [comment]
> Where are you deploying?

Vps 1vCPU - 1GB RAM - 20GB SSD Enterprise Ubuntu 20.04 - hazi-ro

**Comment by Sam-Max** [comment]
Yes, bro you are right, I will fix tomorrow

**Comment by Sam-Max** [comment]
@erickyun fixed now serve

**Comment by erickyun** [comment]
> @erickyun fixed now serve

Yes thank you very much sir.
