### ISSUE TITLE
When using mirror this is happening 

### ISSUE THREAD

**Issue by muktoxxx** [Sam-Max/rclone-mirror-leech-telegram-bot#129]
![SmartSelect_20230329-041236_Telegram](https://user-images.githubusercontent.com/127892044/228739642-53cf9aef-0d7f-445e-aef7-d2d48210a5ad.jpg)
![Screenshot_20230329-042756_Termius](https://user-images.githubusercontent.com/127892044/228739656-1e3d4acd-49ed-4796-8c28-7aa752233761.jpg)

Please check what is the problem already uploaded rclone.conf selected cloud by cloudselect but steel after downloading getting stuck and bot trys to restart it self... Please help

**Comment by Sam-Max** [comment]
Make sure your repo/bot iss updated to last commit first
