### ISSUE TITLE
selection not working? 

### ISSUE THREAD

**Issue by LuisAlfonsoB** [Sam-Max/rclone-mirror-leech-telegram-bot#131]
Hi, It seems selection of files is not working. I do the usual selecting but after clicking "Done selecting" button nothing happens. I checked the logs and this is what I get. I don't know what the issue is to be honest. Thanks for any help.
![image](https://user-images.githubusercontent.com/119376216/230274783-a8a94a90-cab7-4fac-96db-2cc2e7ee7b48.png)

![image](https://user-images.githubusercontent.com/119376216/230274692-8dfed5ca-1c8e-4d10-9df0-b6b56dc2965a.png)

**Comment by Sam-Max** [comment]
It is fixed now
