### ISSUE TITLE
search.py problem

### ISSUE THREAD

**Issue by mr-m85** [Sam-Max/rclone-mirror-leech-telegram-bot#136]
when search in any site with api and the result not found gives error

ex: when result found

rcmltb | 2023-04-24 10:09:18,949 INFO MainThread bot API Trending from yts
rcmltb | 2023-04-24 10:09:22,652 INFO MainThread bot ['Torrent-Search-04-24-104']

Found 15 trending result(s)
Torrent Site:- Yts
view

ex: when result not found

rcmltb | 2023-04-24 10:10:52,893 INFO MainThread bot API Searching: ghftvnhtdg from yts
rcmltb | 2023-04-24 10:10:54,166 ERROR MainThread bot 'str' object has no attribute 'id'

Searching for ghftvnhtdg
Torrent Site:- Yts

it stuck like this

**Comment by Sam-Max** [comment]
> when search in any site with api and the result not found gives error
> 
> ex: when result found
> 
> rcmltb | 2023-04-24 10:09:18,949 INFO MainThread bot API Trending from yts rcmltb | 2023-04-24 10:09:22,652 INFO MainThread bot ['Torrent-Search-04-24-104']
> 
> Found 15 trending result(s) Torrent Site:- Yts view
> 
> ex: when result not found
> 
> rcmltb | 2023-04-24 10:10:52,893 INFO MainThread bot API Searching: ghftvnhtdg from yts rcmltb | 2023-04-24 10:10:54,166 ERROR MainThread bot 'str' object has no attribute 'id'
> 
> Searching for ghftvnhtdg Torrent Site:- Yts
> 
> it stuck like this

Fixed now
