### ISSUE TITLE
ytdlp.py problem

### ISSUE THREAD

**Issue by mr-m85** [Sam-Max/rclone-mirror-leech-telegram-bot#137]
when add this opt:bv*+ba/b in /ytdl cmd to select button automatically not work it redirect you to choose with button
not to start download

what i do to make it select best video button without press on it

**Comment by Sam-Max** [comment]
> when add this opt:bv*+ba/b in /ytdl cmd to select button automatically not work it redirect you to choose with button not to start download
> 
> what i do to make it select best video button without press on it

it should work now
