### ISSUE TITLE
search.py  Error

### ISSUE THREAD

**Issue by mr-m85** [Sam-Max/rclone-mirror-leech-telegram-bot#145]
select any button in search like trending recent not work

![Screenshot 2023-05-24 114008](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/assets/106661735/af1c9d30-7012-4c3e-821c-6f50ab5d3f77)

[botlog (21).txt](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/files/11552368/botlog.21.txt)

search not work at all with api or pligins same error

rcmltb | 2023-05-24 08:39:07,049 - pyrogram.dispatcher - ERROR - list index out of range
rcmltb | Traceback (most recent call last):
rcmltb |   File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
rcmltb |     await handler.callback(self.client, *args)
rcmltb |   File "/usr/src/app/bot/modules/search.py", line 258, in torrentSearchUpdate
rcmltb |     if data[4] is not None:
rcmltb | IndexError: list index out of range

**Comment by Sam-Max** [comment]
Fixed now
