### ISSUE TITLE
Improved Rclone with SA account.

### ISSUE THREAD

**Issue by Namlee123** [Sam-Max/rclone-mirror-leech-telegram-bot#28]
I think your project is awesome. Because me and a lot of others prefer to use Rclone instead of Gd-utils to upload data to Drive.

But it would be great if you could combine a few things:
- Replace Rclone with Gclone, it will help us to clone with ID (Link drive) and use SA to exceed 750g/day limit.
(https://github.com/dogbutcat/gclone)
- Deploy code using "Github Action" on heroku.

Those are small issues that I think if you have time you can improve on it.

**Comment by Sam-Max** [comment]
I  replaced Rclone with Gclone, to clone with ID (Link drive). SA maybe in future. As Heroku no more support as no more free from November

**Comment by b1fly** [comment]
> I replaced Rclone with Gclone, to clone with ID (Link drive). SA maybe in future. As Heroku no more support as no more free from November

thanks open source . 
bro Can a /clean command be added? Although config.env can fill in the download directory, but when I download the file, the directory is still empty, and I can't find this directory, /usr/src/app/downloads, so it may be better to add a clear file command, maybe I found a new bug. After I used the /qbleech command, the capacity of my hard disk was reduced. After the file was downloaded to tg, the capacity of the hard disk did not increase.

Request: Can a multilingual setting be added? Maybe better. This is just my personal request.

**Comment by bolavefasfas** [comment]
> 

If git actions code is added in this repo github will ban this acc so No actions support lol

**Comment by bolavefasfas** [comment]
> I replaced Rclone with Gclone, to clone with ID (Link drive). SA maybe in future. As Heroku no more support as no more free from November

Bro keep updating repo people have paid vps or other services than heroku where they love to use this code

**Comment by Sam-Max** [comment]
> > I replaced Rclone with Gclone, to clone with ID (Link drive). SA maybe in future. As Heroku no more support as no more free from November
> 
> thanks open source . bro Can a /clean command be added? Although config.env can fill in the download directory, but when I download the file, the directory is still empty, and I can't find this directory, /usr/src/app/downloads, so it may be better to add a clear file command, maybe I found a new bug. After I used the /qbleech command, the capacity of my hard disk was reduced. After the file was downloaded to tg, the capacity of the hard disk did not increase.
> 
> Request: Can a multilingual setting be added? Maybe better. This is just my personal request.
> 
> The task is completed, but the file exists on the hard disk and is not automatically cleared！ ![image](https://user-images.githubusercontent.com/108970034/188368812-2f205fab-8286-40e3-9849-46722ff1ae1f.png)

I wil fix clean file after qbleech , maybe I forgot to add. Multilingual setting not for now.  Only English for now
