### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by pachax001** [Sam-Max/rclone-mirror-leech-telegram-bot#52]
I am trying to upload a zip file to my onedrive using an index link.The file downloads successfully.But when uploading the upload happena partially.Upload progress go about 5% then suddenly shows upload complete message.The file is also in my onedrive and it shows the full file size.But when I download the file and try extract it says corrupted zip file.

**Comment by pachax001** [comment]
Here is a video

https://user-images.githubusercontent.com/93702860/196140765-1bbd9c98-2819-420d-b02c-777c3576ba38.mp4

**Comment by pachax001** [comment]
Here is a video of the issue

https://user-images.githubusercontent.com/93702860/196142278-3af41428-2849-482d-8349-70c0ed3dfe8c.mp4

**Comment by Sam-Max** [comment]
> I am trying to upload a zip file to my onedrive using an index link.The file downloads successfully.But when uploading the upload happena partially.Upload progress go about 5% then suddenly shows upload complete message.The file is also in my onedrive and it shows the full file size.But when I download the file and try extract it says corrupted zip file.

First, update bot to last commit to be sure, and after that if it keeps happening write me in private on telegram to test that file

**Comment by pachax001** [comment]
> > I am trying to upload a zip file to my onedrive using an index link.The file downloads successfully.But when uploading the upload happena partially.Upload progress go about 5% then suddenly shows upload complete message.The file is also in my onedrive and it shows the full file size.But when I download the file and try extract it says corrupted zip file.
> 
> First, update bot to last commit to be sure, and after that if it keeps happening write me in private on telegram to test that file

Same happens with any kind of direct link

**Comment by Sam-Max** [comment]
> > > I am trying to upload a zip file to my onedrive using an index link.The file downloads successfully.But when uploading the upload happena partially.Upload progress go about 5% then suddenly shows upload complete message.The file is also in my onedrive and it shows the full file size.But when I download the file and try extract it says corrupted zip file.
> > 
> > 
> > First, update bot to last commit to be sure, and after that if it keeps happening write me in private on telegram to test that file
> 
> Same happens with any kind of direct link

I tried now to mirror a direct link to gdrive and is working fine dude, and no file corrupted after downloaded

**Comment by pachax001** [comment]
> > > > I am trying to upload a zip file to my onedrive using an index link.The file downloads successfully.But when uploading the upload happena partially.Upload progress go about 5% then suddenly shows upload complete message.The file is also in my onedrive and it shows the full file size.But when I download the file and try extract it says corrupted zip file.
> > > 
> > > 
> > > First, update bot to last commit to be sure, and after that if it keeps happening write me in private on telegram to test that file
> > 
> > 
> > Same happens with any kind of direct link
> 
> I tried now to mirror a direct link to gdrive and is working fine dude, and no file corrupted after downloaded

Not gdrive bro.Onedrive

**Comment by pachax001** [comment]
> > > > > I am trying to upload a zip file to my onedrive using an index link.The file downloads successfully.But when uploading the upload happena partially.Upload progress go about 5% then suddenly shows upload complete message.The file is also in my onedrive and it shows the full file size.But when I download the file and try extract it says corrupted zip file.
> > > > 
> > > > 
> > > > First, update bot to last commit to be sure, and after that if it keeps happening write me in private on telegram to test that file
> > > 
> > > 
> > > Same happens with any kind of direct link
> > 
> > 
> > I tried now to mirror a direct link to gdrive and is working fine dude, and no file corrupted after downloaded
> 
> Not gdrive bro.Onedrive

Although the status stops before completing 100% tge whole file gets uploaded to the onedrive.Sorry for the inconvenience.The problem is in status.It doesn't complete like in the above video.
