### ISSUE TITLE
folders from second page in copy menu

### ISSUE THREAD

**Issue by gapemaster3** [Sam-Max/rclone-mirror-leech-telegram-bot#53]
Hi, I have several folders and when trying to /copy a folder from second page it will not open.. folders listed in first page open and I can copy those, however, folders that appear in page 2 onwards do not open.

I have deployed different versions  of repo (anasty-like repo) and the issue remains.
I have an older version of the repo (before anasty-like) and there I can copy whatever folder from any page in the copy menu..

So there might be something wrong in the newest code.. sadly I don't have any logs to show but I suspect it doesn't show in the logs either.
Edit: I just checked latest commit and saw you fixed something in copy module.. so I guess that's the solution.. will deploy and verify.
Edit2: Still same issue..
Thanks for your work!

**Comment by Sam-Max** [comment]
> Hi, I have several folders and when trying to /copy a folder from second page it will not open.. folders listed in first page open and I can copy those, however, folders that appear in page 2 onwards do not open.
> 
> I have deployed different versions of repo (anasty-like repo) and the issue remains. I have an older version of the repo (before anasty-like) and there I can copy whatever folder from any page in the copy menu..
> 
> So there might be something wrong in the newest code.. sadly I don't have any logs to show but I suspect it doesn't show in the logs either. Edit: I just checked latest commit and saw you fixed something in copy module.. so I guess that's the solution.. will deploy and verify. Edit2: Still same issue.. Thanks for your work!

Yes, problem happened when using next or back button inside a folder on both menus. Now is fixed. Restart bot.

**Comment by gapemaster3** [comment]
Thanks for the fix!
