### ISSUE TITLE
Multi Link Mirror support

### ISSUE THREAD

**Issue by pachax001** [Sam-Max/rclone-mirror-leech-telegram-bot#54]
Please add multi link mirror support.

**Comment by Sam-Max** [comment]
> Please add multi link mirror support.

You can use mirrorbatch for multi link mirror

**Comment by Sam-Max** [comment]
> Please add multi link mirror support.

I will add same as anasty

**Comment by pachax001** [comment]
> > Please add multi link mirror support.
> 
> I will add same as anasty

Ok
