### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by bolavefasfas** [Sam-Max/rclone-mirror-leech-telegram-bot#55]
Bro can you remove this flag `--drive-server-side-across-configs` as if we are copying from restricted drive to non restricted drive it throws error if this flag isn't used it works perfectly.
or keep that flag optional with button 
Thanks

**Comment by Sam-Max** [comment]
> 

It is matter of permissions

**Comment by bolavefasfas** [comment]
Yes but for most drives I dont have permission thats the problem 
I mean i am joint in the td as a viewer with google group the admin of the td deny any request to elevated permission 
So can you remove it so create a separate branch for server side copy

**Comment by Sam-Max** [comment]
> 

I will make optional

**Comment by bolavefasfas** [comment]
Waiting, Thanks

**Comment by bolavefasfas** [comment]
Did you make it optional ?

**Comment by Sam-Max** [comment]
> Did you make it optional ?

now is optional, update

**Comment by bolavefasfas** [comment]
Thanks

**Comment by bolavefasfas** [comment]
> > Did you make it optional ?
> 
> now is optional, update

Broo whatever you do plz dont change the upload method like using rclone because this is the only repo that allows to upload from tor,mega,dirlink,tg to encrypted rclone remote
mirrorleechbots are shit as they upload to normal remotes on which data is insecure
