### ISSUE TITLE
(Request) gdtot support

### ISSUE THREAD

**Issue by elricariocco16** [Sam-Max/rclone-mirror-leech-telegram-bot#56]
Hi, is it possible for you to implement gdtot support? [Anasty repo used to have it but he removed it. ](https://github.com/arshsisodiya/helios-mirror)
![image](https://user-images.githubusercontent.com/117310578/200112471-9dc7bf7d-b9f1-4973-8a77-dc6d0ce0dfdb.png)

**Comment by bolavefasfas** [comment]
+1

**Comment by Sam-Max** [comment]
I heard that it is not stable

**Comment by rinrinx** [comment]
Do not add such things, it is always more logical to add plugins, not global
