### ISSUE TITLE
Doesn't fetch from upstream on restart

### ISSUE THREAD

**Issue by anymeofu** [Sam-Max/rclone-mirror-leech-telegram-bot#58]
I have made changes in repo present in upstream , but on restart it doesn't get updated,
I have to manually pull from git and build docker images again and restart docker in order to get the changes I did in upstream repo.
PS: I am using a VPS Ubuntu 18 with docker

**Comment by Sam-Max** [comment]
It is working fine, I use all the time.

**Comment by anymeofu** [comment]
okay will redeploy again !
