### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by bolavefasfas** [Sam-Max/rclone-mirror-leech-telegram-bot#60]
To be able to select which remote to select before every mirror or clone with time like 30 seconds and no remote is selected it defaults to the default remote

This is already implemented in https://github.com/junedkh/jmdkh-mltb this repo **but We cant ise encrypted remotes in this** 

Which we can in your repo, can you add the category select or ability to select the rclone remote before every time we mirror clone or do anything.

and maybe buttons 
![image](https://user-images.githubusercontent.com/82230241/202861457-7d087773-24f8-419f-b0df-a38bbc9c6d9a.png)

This is in category button 

![image](https://user-images.githubusercontent.com/82230241/202861263-57b29d02-0c90-4988-86f6-d4d9001ce09f.png)

**Comment by Sam-Max** [comment]
Not bad idea. Thanks for suggestion.

**Comment by bolavefasfas** [comment]
Waiting for this feature. Thanks For reply eta ??
1 week ? or less

**Comment by bolavefasfas** [comment]
Bro can you add the category feature ? it would be a lot easier just add one more var like if we cant the category feature or want to download to default mirror set

**Comment by Sam-Max** [comment]
> Bro Please update this feature

Done
