### ISSUE TITLE
help

### ISSUE THREAD

**Issue by elricariocco16** [Sam-Max/rclone-mirror-leech-telegram-bot#64]
https://patr.cloud/
https://docs.patr.cloud/pricing/free-allowance/
![image](https://user-images.githubusercontent.com/117310578/205445882-9a626a2d-6ad0-44f4-85c8-ddd4e6c1f19a.png)

I want to deploy here, I connect my repo to the account but I apparently I need to create a file in root repo or something. Please refer to this https://docs.patr.cloud/ci-cd/
Basically what I need is the .drone.yml file to deploy the repo. Thanks for any help in advance. 

Edit: I'll also share this repo that might have features of your liking for you to implement in your repo, which is already great.
https://github.com/elricariocco16/ARPT-Bot-English (original repo is https://github.com/666wcy/ARPT-Bot) who knows maybe you like something of it.

**Comment by Sam-Max** [comment]
> https://patr.cloud/ https://docs.patr.cloud/pricing/free-allowance/ ![image](https://user-images.githubusercontent.com/117310578/205445882-9a626a2d-6ad0-44f4-85c8-ddd4e6c1f19a.png)
> 
> I want to deploy here, I connect my repo to the account but I apparently I need to create a file in root repo or something. Please refer to this https://docs.patr.cloud/ci-cd/ Basically what I need is the .drone.yml file to deploy the repo. Thanks for any help in advance.
> 
> Edit: I'll also share this repo that might have features of your liking for you to implement in your repo, which is already great. https://github.com/elricariocco16/ARPT-Bot-English (original repo is https://github.com/666wcy/ARPT-Bot) who knows maybe you like something of it.

OK, thanks for other repo, I will check. As deployent, checon on web how to make .drone.yml
