### ISSUE TITLE
feature request - Mirror logs

### ISSUE THREAD

**Issue by elricariocco16** [Sam-Max/rclone-mirror-leech-telegram-bot#65]
Could you implement mirror logs, please? There is dump for leech but a dump for mirrors would be nice as well to keep everything in its place, nice and organized.
You can refer to https://github.com/arshsisodiya/helios-mirror if you decide to add it.
![image](https://user-images.githubusercontent.com/117310578/205463377-b4e901d3-bf9d-4651-b732-219432b72275.png)

**Comment by Sam-Max** [comment]
> Could you implement mirror logs, please? There is dump for leech but a dump for mirrors would be nice as well to keep everything in its place, nice and organized. You can refer to https://github.com/arshsisodiya/helios-mirror if you decide to add it. ![image](https://user-images.githubusercontent.com/117310578/205463377-b4e901d3-bf9d-4651-b732-219432b72275.png)

Explain in telegram group what it is the use of those

**Comment by Sam-Max** [comment]
> Could you implement mirror logs, please? There is dump for leech but a dump for mirrors would be nice as well to keep everything in its place, nice and organized. You can refer to https://github.com/arshsisodiya/helios-mirror if you decide to add it. ![image](https://user-images.githubusercontent.com/117310578/205463377-b4e901d3-bf9d-4651-b732-219432b72275.png)

I added LEECH_LOGS
