### ISSUE TITLE
Pyrogram connection timeout

### ISSUE THREAD

**Issue by nnhieu97** [Sam-Max/rclone-mirror-leech-telegram-bot#67]
Hi. I have deployed it on okteto successfully. I get an error when copying a folder using rclone. This folder contains 4 files, 3 GB each. The bot stopped working at that moment. Before that I had successfully copied some smaller files (several hundred MB)
`app-5b4c54b59f-pd6wnapp2022-12-07 14:00:46,576 WARNING MainThread pyrogram.connection.connection Unable to connect due to network issues: timed out
app-5b4c54b59f-pd6wnapp2022-12-07 14:00:46,952 INFO MainThread pyrogram.connection.connection Connecting...
app-5b4c54b59f-pd6wnapp2022-12-07 14:00:47,580 INFO MainThread pyrogram.connection.connection Connecting...
app-5b4c54b59f-pd6wnapp2022-12-07 14:00:53,439 INFO MainThread pyrogram.session.session [2] Retrying "messages.EditMessage" due to Value after * must be an iterable, not NoneType
app-5b4c54b59f-pd6wnapp2022-12-07 14:00:56,963 WARNING MainThread pyrogram.connection.connection Unable to connect due to network issues: timed out`

**Comment by Sam-Max** [comment]
> 

It seems like a network problem, on okteto

**Comment by nnhieu97** [comment]
Yes it's okteto's network problem. The copying process is still going normally, it's just that the bot is not responding
