### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by theseeker99** [Sam-Max/rclone-mirror-leech-telegram-bot#69]
If user uses a custom rclone config file Bot's mirror part is working fine. But cloning is not. Bot gives this error 

Error.
HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1NIZOCzyQL1cGTQoYn5a2yY4edxKydX27?supportsTeamDrives=true&fields=name%2C+id%2C+mimeType%2C+size&alt=json returned "Request had insufficient authentication scopes.". Details: "[{'message': 'Insufficient Permission', 'domain': 'global', 'reason': 'insufficientPermissions'}]"

How to fix this?

**Comment by rinrinx** [comment]
Add token pickle on bot

**Comment by theseeker99** [comment]
> Add token pickle on bot

I added bro

**Comment by Sam-Max** [comment]
> If user uses a custom rclone config file Bot's mirror part is working fine. But cloning is not. Bot gives this error
> 
> Error. HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1NIZOCzyQL1cGTQoYn5a2yY4edxKydX27?supportsTeamDrives=true&fields=name%2C+id%2C+mimeType%2C+size&alt=json returned "Request had insufficient authentication scopes.". Details: "[{'message': 'Insufficient Permission', 'domain': 'global', 'reason': 'insufficientPermissions'}]"
> 
> How to fix this?

You don't have permission for link you are cloning
