### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by carolynsteeves1** [Sam-Max/rclone-mirror-leech-telegram-bot#70]
app_1  | 2022-12-11 22:41:15,462 WARNING MainThread bot BASE_URL not provided!
app_1  | 2022-12-11 22:41:15,462 INFO MainThread bot Creating Pyrogram client
app_1  | [2022-12-11 22:41:15 +0000] [11] [INFO] Starting gunicorn 20.1.0
app_1  | [2022-12-11 22:41:15 +0000] [11] [INFO] Listening at: http://0.0.0.0:80 (11)
app_1  | [2022-12-11 22:41:15 +0000] [11] [INFO] Using worker: sync
app_1  | [2022-12-11 22:41:15 +0000] [36] [INFO] Booting worker with pid: 36
app_1  | Initiliazing Library with API_KEY: VfsUQZ5B
app_1  | 2022/12/11 22:41:16 Serving on TCP :6090
app_1  | [GIN] 2022/12/11 - 22:41:21 | 200 |  2.545493008s |       127.0.0.1 | POST     "/login"
app_1  | 2022-12-11 22:41:21,698 INFO Thread-1 (aria2c_init) bot Initializing Aria2c
app_1  | 2022-12-11 22:41:23,980 INFO MainThread bot Creating Telegraph Account
app_1  | /usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
app_1  |   warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
app_1  | 2022-12-11 22:41:24,248 INFO MainThread apscheduler.scheduler Adding job tentatively -- it will be properly scheduled when the scheduler starts
app_1  | 2022-12-11 22:41:24,248 INFO MainThread apscheduler.scheduler Added job "rss_monitor" to job store "default"
app_1  | 2022-12-11 22:41:24,248 INFO MainThread apscheduler.scheduler Scheduler started
app_1  | Successfully deployed!
app_1  | 2022-12-11 22:41:24,489 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC2
app_1  | 2022-12-11 22:41:24,489 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-11 22:41:24,576 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO
app_1  | 2022-12-11 22:41:25,809 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk
app_1  | 2022-12-11 22:41:25,810 INFO MainThread pyrogram.connection.connection Disconnected
app_1  | 2022-12-11 22:41:25,816 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-11 22:41:25,904 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO
app_1  | 2022-12-11 22:41:25,904 INFO MainThread pyrogram.session.session NetworkTask started
app_1  | 2022-12-11 22:41:26,123 INFO MainThread pyrogram.session.internals.msg_id Time synced: 2022-12-11 22:41:26.081886 UTC
app_1  | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session Session initialized: Layer 150
app_1  | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.69
app_1  | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1021-oracle (EN)
app_1  | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session Session started
app_1  | 2022-12-11 22:41:26,306 INFO MainThread pyrogram.session.session PingTask started
app_1  | 2022-12-11 22:41:26,400 INFO MainThread pyrogram.session.session PingTask stopped
app_1  | 2022-12-11 22:41:26,400 INFO MainThread pyrogram.connection.connection Disconnected
app_1  | 2022-12-11 22:41:26,401 INFO MainThread pyrogram.session.session NetworkTask stopped
app_1  | 2022-12-11 22:41:26,401 INFO MainThread pyrogram.session.session Session stopped
app_1  | 2022-12-11 22:41:26,408 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC1
app_1  | 2022-12-11 22:41:26,408 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-11 22:41:26,438 INFO MainThread pyrogram.connection.connection Connected! Production DC1 - IPv4 - TCPAbridgedO
app_1  | 2022-12-11 22:41:27,495 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk
app_1  | 2022-12-11 22:41:27,496 INFO MainThread pyrogram.connection.connection Disconnected
app_1  | 2022-12-11 22:41:27,502 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-11 22:41:27,532 INFO MainThread pyrogram.connection.connection Connected! Production DC1 - IPv4 - TCPAbridgedO
app_1  | 2022-12-11 22:41:27,532 INFO MainThread pyrogram.session.session NetworkTask started
app_1  | 2022-12-11 22:41:27,702 INFO MainThread pyrogram.session.session Session initialized: Layer 150
app_1  | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.69
app_1  | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1021-oracle (EN)
app_1  | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session Session started
app_1  | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session PingTask started
app_1  | 2022-12-11 22:41:27,835 INFO MainThread pyrogram.dispatcher Started 8 HandlerTasks

**Comment by Sam-Max** [comment]
> app_1 | 2022-12-11 22:41:15,462 WARNING MainThread bot BASE_URL not provided! app_1 | 2022-12-11 22:41:15,462 INFO MainThread bot Creating Pyrogram client app_1 | [2022-12-11 22:41:15 +0000] [11] [INFO] Starting gunicorn 20.1.0 app_1 | [2022-12-11 22:41:15 +0000] [11] [INFO] Listening at: http://0.0.0.0:80 (11) app_1 | [2022-12-11 22:41:15 +0000] [11] [INFO] Using worker: sync app_1 | [2022-12-11 22:41:15 +0000] [36] [INFO] Booting worker with pid: 36 app_1 | Initiliazing Library with API_KEY: VfsUQZ5B app_1 | 2022/12/11 22:41:16 Serving on TCP :6090 app_1 | [GIN] 2022/12/11 - 22:41:21 | 200 | 2.545493008s | 127.0.0.1 | POST "/login" app_1 | 2022-12-11 22:41:21,698 INFO Thread-1 (aria2c_init) bot Initializing Aria2c app_1 | 2022-12-11 22:41:23,980 INFO MainThread bot Creating Telegraph Account app_1 | /usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC. app_1 | warnings.warn("Can not find any timezone configuration, defaulting to UTC.") app_1 | 2022-12-11 22:41:24,248 INFO MainThread apscheduler.scheduler Adding job tentatively -- it will be properly scheduled when the scheduler starts app_1 | 2022-12-11 22:41:24,248 INFO MainThread apscheduler.scheduler Added job "rss_monitor" to job store "default" app_1 | 2022-12-11 22:41:24,248 INFO MainThread apscheduler.scheduler Scheduler started app_1 | Successfully deployed! app_1 | 2022-12-11 22:41:24,489 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC2 app_1 | 2022-12-11 22:41:24,489 INFO MainThread pyrogram.connection.connection Connecting... app_1 | 2022-12-11 22:41:24,576 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO app_1 | 2022-12-11 22:41:25,809 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk app_1 | 2022-12-11 22:41:25,810 INFO MainThread pyrogram.connection.connection Disconnected app_1 | 2022-12-11 22:41:25,816 INFO MainThread pyrogram.connection.connection Connecting... app_1 | 2022-12-11 22:41:25,904 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO app_1 | 2022-12-11 22:41:25,904 INFO MainThread pyrogram.session.session NetworkTask started app_1 | 2022-12-11 22:41:26,123 INFO MainThread pyrogram.session.internals.msg_id Time synced: 2022-12-11 22:41:26.081886 UTC app_1 | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session Session initialized: Layer 150 app_1 | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.69 app_1 | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1021-oracle (EN) app_1 | 2022-12-11 22:41:26,305 INFO MainThread pyrogram.session.session Session started app_1 | 2022-12-11 22:41:26,306 INFO MainThread pyrogram.session.session PingTask started app_1 | 2022-12-11 22:41:26,400 INFO MainThread pyrogram.session.session PingTask stopped app_1 | 2022-12-11 22:41:26,400 INFO MainThread pyrogram.connection.connection Disconnected app_1 | 2022-12-11 22:41:26,401 INFO MainThread pyrogram.session.session NetworkTask stopped app_1 | 2022-12-11 22:41:26,401 INFO MainThread pyrogram.session.session Session stopped app_1 | 2022-12-11 22:41:26,408 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC1 app_1 | 2022-12-11 22:41:26,408 INFO MainThread pyrogram.connection.connection Connecting... app_1 | 2022-12-11 22:41:26,438 INFO MainThread pyrogram.connection.connection Connected! Production DC1 - IPv4 - TCPAbridgedO app_1 | 2022-12-11 22:41:27,495 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk app_1 | 2022-12-11 22:41:27,496 INFO MainThread pyrogram.connection.connection Disconnected app_1 | 2022-12-11 22:41:27,502 INFO MainThread pyrogram.connection.connection Connecting... app_1 | 2022-12-11 22:41:27,532 INFO MainThread pyrogram.connection.connection Connected! Production DC1 - IPv4 - TCPAbridgedO app_1 | 2022-12-11 22:41:27,532 INFO MainThread pyrogram.session.session NetworkTask started app_1 | 2022-12-11 22:41:27,702 INFO MainThread pyrogram.session.session Session initialized: Layer 150 app_1 | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.69 app_1 | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1021-oracle (EN) app_1 | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session Session started app_1 | 2022-12-11 22:41:27,703 INFO MainThread pyrogram.session.session PingTask started app_1 | 2022-12-11 22:41:27,835 INFO MainThread pyrogram.dispatcher Started 8 HandlerTasks

What is the problem?

**Comment by Sam-Max** [comment]
What is the problem?

**Comment by carolynsteeves1** [comment]
> What is the problem?

that bot doesnt work, it just says this after docker-compose up

**Comment by carolynsteeves1** [comment]
Removing intermediate container fe36d3c22eb3
 ---> 0104aa1425f9
Step 8/9 : COPY . .
 ---> da0981a92329
Step 9/9 : CMD ["bash","start.sh"]
 ---> Running in 478a75b0bf51
Removing intermediate container 478a75b0bf51
 ---> 52561bf28bde
Successfully built 52561bf28bde
Successfully tagged rclone-mirror-leech-telegram-bot_app:latest
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating rclone-mirror-leech-telegram-bot_app_1 ... done
Attaching to rclone-mirror-leech-telegram-bot_app_1
app_1  | 2022-12-13 22:12:19,306 WARNING MainThread bot BASE_URL not provided!
app_1  | 2022-12-13 22:12:19,307 INFO MainThread bot Creating Pyrogram client
app_1  | [2022-12-13 22:12:19 +0000] [10] [INFO] Starting gunicorn 20.1.0
app_1  | [2022-12-13 22:12:19 +0000] [10] [INFO] Listening at: http://0.0.0.0:80 (10)
app_1  | [2022-12-13 22:12:19 +0000] [10] [INFO] Using worker: sync
app_1  | [2022-12-13 22:12:19 +0000] [35] [INFO] Booting worker with pid: 35
app_1  | Initiliazing Library with API_KEY: VfsUQZ5B
app_1  | 2022/12/13 22:12:20 Serving on TCP :6090
app_1  | [GIN] 2022/12/13 - 22:12:26 | 200 |  3.397217035s |       127.0.0.1 | POST     "/login"
app_1  | 2022-12-13 22:12:26,742 INFO Thread-1 (aria2c_init) bot Initializing Aria2c
app_1  | 2022-12-13 22:12:29,051 INFO MainThread bot Creating Telegraph Account
app_1  | /usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
app_1  |   warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
app_1  | 2022-12-13 22:12:29,612 INFO MainThread apscheduler.scheduler Adding job tentatively -- it will be properly scheduled when the scheduler starts
app_1  | 2022-12-13 22:12:29,618 INFO MainThread apscheduler.scheduler Added job "rss_monitor" to job store "default"
app_1  | 2022-12-13 22:12:29,619 INFO MainThread apscheduler.scheduler Scheduler started
app_1  | Successfully deployed!!
app_1  | 2022-12-13 22:12:30,209 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC2
app_1  | 2022-12-13 22:12:30,213 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-13 22:12:30,307 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO
app_1  | 2022-12-13 22:12:32,158 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk
app_1  | 2022-12-13 22:12:32,162 INFO MainThread pyrogram.connection.connection Disconnected
app_1  | 2022-12-13 22:12:32,186 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-13 22:12:32,299 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO
app_1  | 2022-12-13 22:12:32,311 INFO MainThread pyrogram.session.session NetworkTask started
app_1  | 2022-12-13 22:12:32,516 INFO MainThread pyrogram.session.internals.msg_id Time synced: 2022-12-13 22:12:32.454356 UTC
app_1  | 2022-12-13 22:12:32,703 INFO MainThread pyrogram.session.session Session initialized: Layer 150
app_1  | 2022-12-13 22:12:32,704 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.70
app_1  | 2022-12-13 22:12:32,704 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1021-oracle (EN)
app_1  | 2022-12-13 22:12:32,705 INFO MainThread pyrogram.session.session Session started
app_1  | 2022-12-13 22:12:32,706 INFO MainThread pyrogram.session.session PingTask started
app_1  | 2022-12-13 22:12:32,805 INFO MainThread pyrogram.session.session PingTask stopped
app_1  | 2022-12-13 22:12:32,807 INFO MainThread pyrogram.connection.connection Disconnected
app_1  | 2022-12-13 22:12:32,808 INFO MainThread pyrogram.session.session NetworkTask stopped
app_1  | 2022-12-13 22:12:32,810 INFO MainThread pyrogram.session.session Session stopped
app_1  | 2022-12-13 22:12:32,840 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC1
app_1  | 2022-12-13 22:12:32,850 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-13 22:12:32,884 INFO MainThread pyrogram.connection.connection Connected! Production DC1 - IPv4 - TCPAbridgedO
app_1  | 2022-12-13 22:12:34,113 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk
app_1  | 2022-12-13 22:12:34,122 INFO MainThread pyrogram.connection.connection Disconnected
app_1  | 2022-12-13 22:12:34,140 INFO MainThread pyrogram.connection.connection Connecting...
app_1  | 2022-12-13 22:12:34,175 INFO MainThread pyrogram.connection.connection Connected! Production DC1 - IPv4 - TCPAbridgedO
app_1  | 2022-12-13 22:12:34,176 INFO MainThread pyrogram.session.session NetworkTask started
app_1  | 2022-12-13 22:12:34,357 INFO MainThread pyrogram.session.session Session initialized: Layer 150
app_1  | 2022-12-13 22:12:34,358 INFO MainThread pyrogram.session.session Device: CPython 3.10.6 - Pyrogram 2.0.70
app_1  | 2022-12-13 22:12:34,360 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1021-oracle (EN)
app_1  | 2022-12-13 22:12:34,366 INFO MainThread pyrogram.session.session Session started
app_1  | 2022-12-13 22:12:34,368 INFO MainThread pyrogram.session.session PingTask started
app_1  | 2022-12-13 22:12:34,527 INFO MainThread pyrogram.dispatcher Started 5 HandlerTasks

---


then nothing happens after this. Bot doesnt reply or start
