### ISSUE TITLE
'app' failed to build

### ISSUE THREAD

**Issue by nnhieu97** [Sam-Max/rclone-mirror-leech-telegram-bot#72]
Hi. I  on vps debian and get this error. It shows up on command docker-compose up.Can you help me to solve it?
![error](https://user-images.githubusercontent.com/61255069/207755671-fd43c0fb-cc33-4b0d-8bf4-b344b4235a63.png)

**Comment by rinrinx** [comment]
Install python and pip

**Comment by nnhieu97** [comment]
python 3.9.2 and pip 20.3.4 already installed. but the error still repeats
