### ISSUE TITLE
Please keep the dockerfile public 

### ISSUE THREAD

**Issue by bolavefasfas** [Sam-Max/rclone-mirror-leech-telegram-bot#73]
Anas dockerfile may have cryptominer or god knows what please keep your old dockerfile its working properly.

**Comment by Sam-Max** [comment]
> 

Do you think so?

**Comment by missemily22** [comment]
@Sam-Max Maybe @bolavefasfas is not entirely wrong
Many suspect Anas` Dockerfile but I cannot confirm if its true

**Comment by missemily22** [comment]
@bolavefasfas I have done according to your request
We now use a Custom Docker
See #74 for Details

**Comment by bolavefasfas** [comment]
> > 
> 
> Do you think so?

Yes
