### ISSUE TITLE
error mirror .aria2 

### ISSUE THREAD

**Issue by tawayaka** [Sam-Max/rclone-mirror-leech-telegram-bot#75]
i use bot to mirror but somehow there is ".aria2" after my image, i tried deleting ".aria2" but the image doesn't work
![image](https://user-images.githubusercontent.com/30314539/209462963-616b3369-efaf-4e9a-bb0a-fa18fbdaade4.png)

**Comment by Gapemaster6** [comment]
yes this is annoying issue, it happens with videos too. for example video.mp4 is uploaded but also video.mp4.aria2, which I have to manually delete afterwards.
Do not pay attention to the .aria2 file, in your screenshot, the actual picture is "rdsz9gq.jpg".

Please Sam fix if possible that additional file creation. Thanks.

**Comment by Sam-Max** [comment]
> .

Yees, I will fix

**Comment by Sam-Max** [comment]
> yes this is annoying issue, it happens with videos too. for example video.mp4 is uploaded but also video.mp4.aria2, which I have to manually delete afterwards. Do not pay attention to the .aria2 file, in your screenshot, the actual picture is "rdsz9gq.jpg".
> 
> Please Sam fix if possible that additional file creation. Thanks.

FIxed
