### ISSUE TITLE
Module errors

### ISSUE THREAD

**Issue by MinorX** [Sam-Max/rclone-mirror-leech-telegram-bot#76]
Hi. I know that this is pretty lame to ask and I know that i could have fixed it myself by surfing the web, but it should not happen but is happening to only me ig.
The bot goes module errors while deploying using docker or docker compose both.

It says module "telegram" not available , which i then install using *python3 install python-telegram-bot*. 
After this it says that megasdkclient not available. And i cannot fix this. Please guide me what to do.

**Comment by Gapemaster6** [comment]
try using anasty image maybe that will fix it temporarily while Sam answers

**Comment by MinorX** [comment]
> try using anasty image maybe that will fix it temporarily while Sam answers

I'm just not able to find the megasdkrestclient module. I tried installing *mega.py* by putting it in requirements.txtx but still didn't change anything.
