### ISSUE TITLE
Error when deploy okteto

### ISSUE THREAD

**Issue by tuthanika** [Sam-Max/rclone-mirror-leech-telegram-bot#77]
Run"Load manifest"
Found okteto compose manifest on docker-compose.ymlUnmarshalling compose...x Syntax error volumes should be 'local_path:remote_path' or 'remote_path'exit status 1

**Comment by Sam-Max** [comment]
> Run"Load manifest" Found okteto compose manifest on docker-compose.ymlUnmarshalling compose...x Syntax error volumes should be 'local_path:remote_path' or 'remote_path'exit status 1

Only support for VPS/PC
