### ISSUE TITLE
(request) Bulk download from txt file

### ISSUE THREAD

**Issue by Gapemaster6** [Sam-Max/rclone-mirror-leech-telegram-bot#79]
Hi, Could you please implement something like this bulkdownloader https://github.com/X-Gorn/BulkLoader
![image](https://user-images.githubusercontent.com/121523855/210122740-59357813-b034-4092-a98a-b69c1ff34e23.png)

It is great because allows to send all links together instead of 1 by 1. It also provides the option to save them all as zip if desired.
![image](https://user-images.githubusercontent.com/121523855/210122797-87f436b3-b4f9-4f57-af6a-a5179a5b7039.png)

**Comment by Sam-Max** [comment]
Done
