### ISSUE TITLE
Running on Render

### ISSUE THREAD

**Issue by luoisz** [Sam-Max/rclone-mirror-leech-telegram-bot#80]
When I deploy on Render, this error show “ cannot start pyrogram.dispatcher 12 handler task” and then fail to deploy. Why? and How can I fix?

**Comment by luoisz** [comment]
[
![](https://telegra.ph/file/1014261c39f09823d88a5.jpg)
](url)

**Comment by khainee** [comment]
Don't deploy on render you will got banned after one day

**Comment by tawayaka** [comment]
Only support for VPS/PC

**Comment by saikrishnaegcc2** [comment]
> Only support for VPS/PC

works with heroku paid paln...?
