### ISSUE TITLE
bot unable to recognize what remote I chose after latest update

### ISSUE THREAD

**Issue by jackthenewbie** [Sam-Max/rclone-mirror-leech-telegram-bot#84]
![image](https://user-images.githubusercontent.com/55600733/210928384-d24e7f77-d3a1-43b3-8b78-a8eab123b720.png)
There's nothing unusual in logs https://logpaste.com/wGDdrYK2

**Comment by jackthenewbie** [comment]
1d6809dd118672bca94a23a180785aa372812ef4 isn't fixing this problem, i just rebuild image, still didn't work

**Comment by Sam-Max** [comment]
> 

It only happens on multi selection mode. I will check

**Comment by Sam-Max** [comment]
> [1d6809d](https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot/commit/1d6809dd118672bca94a23a180785aa372812ef4) isn't fixing this problem, i just rebuild image, still didn't work

Fixed now

**Comment by jackthenewbie** [comment]
Rebuild image. 1122263a4a56598344133e77b7e8801d763cab55 does work.
